### ISSUE TITLE
파싱 형식 받기

### ISSUE THREAD

**Issue by Arkingco** [Arkingco/42_cub3d#16]
### ISSUE
 * Type: `feature`
 * Detail: 파싱에서 게임쪽으로 받아올 부분 정하기

``` 
typedef struct s_game
{
	char		         **map;
	int			mini_width;
	int			mini_height;
	char  		*texture_path[4]
	int			floor[3];
	int			ceiling[3];
}	t_game;

```

- 맵의 크기를 받아와야함
    - 맵[y][x]값으로 처리 중
    - 실제 맵의 width 크기
    - 실제 맵의 height 크기
    - 동서남북 텍스처의 주소값
    - 바닥색 코드값
    - 천장색코드값

정도 있으면 될 것 같습니다!

**Comment by brixxt27** [comment]
mini_width, mini_height 는 미니맵에서만 사용하는 값이 아니므로 map_width, map_height 로 사용할 예정이고, 음수는 사용 안 하니까 size_t 로 사용할 것 같아요~

**Comment by Arkingco** [comment]
알겠습니다!
