### ISSUE TITLE
so_long 과 libft 에서 struct s_list 자료형이 둘 다 선언 되어 있다

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_cub3d#6]
### ISSUE
 * Detail: so_long 과 libft 에서 struct s_list 자료형이 둘 다 선언 되어 있다
 
 ### TODO
- [ ] so_long.h 의 s_list 내용을 변경할 예정

**Comment by Arkingco** [comment]
이거 지금 pr 을 올려서 한번 동기화 작업을 진행 하는게 낫겠네여

**Comment by Arkingco** [comment]
끝!
