### ISSUE TITLE
issue 생성 시 type 을 적지 않고 label 로 하면 바깥에서도 분류하기 편하여 없애고 label 로 구분하려 함

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_cub3d#7]
### ISSUE
 * Detail: issue 생성 시 type 을 적지 않고 label 로 하면 바깥에서도 분류하기 편하여 없애고 label 로 구분하려 함
 
 ### TODO
- [x] .git 디렉토리 ISSUE_TEMPLATE.md 변경

**Comment by Arkingco** [comment]
확인!
